Traduction de l'article anglais prévu pour la sortie de darktable 2.6
moy/dtorg pull request #1
Opened 2018-12-02 22:11 UTC by Nilvus

Traduction de l'article de mmoy pour la sortie de darktable 2.6.
Commentaires et aide bienvenue.

2018-12-03 07:35 UTC, moy requested changes
Quelques bricoles en commentaires.

Pour la suite, comme tu veux : soit tu te déclare "responsable de traduction" et c'est ton dépôt qui fait référence, soit je merge en on considère que c'est mon dépôt la référence. Sinon on passe sur linuxfr (petite préférence de ma part pour cette dernière solution pour les contributeurs non-utilisateurs de Git).

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +de récentes versions introduirent des fonctionnalités, habituellement disponibles uniquement
J'aurais utilisé un ton plus informel (le passé simple met une distance avec le lecteur).

```suggestion
les dernières versions ont introduit des fonctionnalités habituellement réservées 
```

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +dans des éditeurs orientés pixels tel que GIMP, comme le module "liquéfier".
```suggestion
aux éditeurs orientés pixels tel que GIMP, comme le module "liquéfier". 
```

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +faire avec le précédent est disponible dans le module "retouche".
```suggestion
faire avec le précédent reste disponible dans le module "retouche".
```
?

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +#### Clonage continu, de meilleurs résultats en moins d'efforts
Attention, le "continu" c'est autre chose. Là, on parle de l'outil "heal" en anglais, traduit par "outil de correction" dans dt en français, et "correcteur" dans GIMP :

https://docs.gimp.org/fr/gimp-tool-heal.html

```suggestion
#### Outil de correction, de meilleurs résultats en moins d'efforts
```

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +Par défaut, la copie utilises un algorithme de "clonage continu"
```suggestion
Par défaut, la copie utilise un algorithme de "correction"  (*heal* en anglais)
```

(J'aime bien garder le jargon anglais, pas mal de gens dont moi apprécient de lire des trucs en français mais ont leur interface configurée en anglais)

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +![Retouche de correction par couleurs différentes](rt-heal-red-white-blue.png)
```suggestion
![Retouche de correction sur des couleurs différentes](rt-heal-red-white-blue.png)
```

?

2018-12-03 07:35 UTC, moy commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +Utilisez simplement la combinaison Control-clic sur l'un des outils
```suggestion
Utilisez simplement la combinaison Contrôle-clic sur l'un des outils 
```

2018-12-03 10:45 UTC, jpg54 commented
Je viens de faire des copies d'écran : https://drive.google.com/drive/folders/1...sp=sharing
Je n'ai pas pu saisir le pointeur de la souris.
Pour les copies d'écran qui sont liées avec une photo , c'est un peu plus compliqué et peut-être faites par l'auteur ?
Bizarre, le ne trouve pas l'équivalent d'auto crop de "correction de perspectives" avec la dernière version que j'ai compilée ?

2018-12-03 11:43 UTC, moy commented
> Je viens de faire des copies d'écran : https://drive.google.com/drive/folders/1...sp=sharing

Le lien est cassé (les `...` sont litéralement dans l'URL).

> Je n'ai pas pu saisir le pointeur de la souris.

Pour celles qui incluent le pointeur de souris, j'ai fait avec Gimp, il y a une case à cocher pour ça.

> Pour les copies d'écran qui sont liées avec une photo , c'est un peu plus compliqué et peut-être faites par l'auteur ?

Oui, je pourrai m'en occuper.

> Bizarre, le ne trouve pas l'équivalent d'auto crop de "correction de perspectives" avec la dernière version que j'ai compilée ?

C'est dans master depuis quelques jours ou semaines. As-tu bien supprimé le répertoire d'install avant de relancer la compilation de la nouvelle version ?

2018-12-03 12:21 UTC, jpg54 commented
https://drive.google.com/drive/folders/1jTtz7ZOeD_pNN7-16WXOlrdKTTe0eVoR?usp=sharing
Ca devrait marché !

2018-12-03 21:15 UTC, jpg54 commented
J'ai vu que la fonction est utilisable avec recadrage en utilisant format d'origine avec un clic continu de la souris.

2018-12-04 07:38 UTC, jpg54 commented
J'ai vu que la fonction est utilisable avec recadrage en utilisant format d'origine avec un clic continu de la souris.

2018-12-04 13:16 UTC, jpg54 commented
J'ai réussi à convertir une image avec une copie d'un module en français, merci Matthieu, je n'avais pas utilisé Gimp pour faire des copies d'écran. C'est bien plus facile pour faire la conversion vers la version française.
Je viens d'en mettre un première dans le répertoire donc j'ai donné le lien plus haut.

2018-12-04 18:44 UTC, moy commented
@Nilvus : tu as vu les commentaires que j'ai laissé sur la pull-request ? Tu t'occupes de les prendre en compte (ou de ne pas être d’accord avec ;-) ), ou tu veux que je le fasse ?

2018-12-04 19:26 UTC, Nilvus commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +Par défaut, la copie utilises un algorithme de "clonage continu"
Ok pour moi. Par contre ta suggestion ferait beaucoup de parenthèses à la suite (il y a déjà la référence à GIMP entre parenthèses). Du coup, je prends ta correction, mais mets la note sur GIMP entre virgules au lieu des parenthèses.
```

2018-12-04 19:33 UTC, Nilvus commented on content/blog/2018-12-25-darktable-2.6/2018-12-25-darktable-2.6-fr.md
> +de récentes versions introduirent des fonctionnalités, habituellement disponibles uniquement
Je le trouvais sympa ce "introduirent" ;-)
Plus sérieusement, tu as raison, c'est corrigé !

2018-12-04 19:38 UTC, Nilvus reviewed
Merci pour tes propositions qui me vont bien (avec un simple amendement pour l'une d'elles). J'ai repris le tout sur Linuxfr. Je propose de reprendre sur Linuxfr. Je ferais quelques copier-coller de temps à autre sur Github histoire d'avoir une autre copie au cas où.

2018-12-04 20:04 UTC, merged